id: I8FE40991
legacy_id: P000301
ocr_import_info:
  bdrc_scan_id: W2PD14777
  source: bdrc
  ocr_info:
    timestamp: '2020-03-10T18:11:55'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T09:19:08.420092+00:00'
last_modified: 2022-09-03 17:42:36.675189
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD14777
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2PD14777
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུད་སྡེ་ཀུན་བཏུས། （རྫོང་སར་གློག་ཀླད་པར་མ།）
statistics:
  ocr_word_mean_confidence_index: 0.9338372416431611
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I2PD14807:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14807
      total_pages: 756
      volume_number: 29
      volume_pages_bdrc_intro: 2
    order: 29
    base_file: I2PD14807.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9444729858401858
    legacy_id: v029
  I2PD14797:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14797
      total_pages: 818
      volume_number: 19
      volume_pages_bdrc_intro: 2
    order: 19
    base_file: I2PD14797.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9328827361980607
    legacy_id: v019
  I2PD14800:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14800
      total_pages: 910
      volume_number: 22
      volume_pages_bdrc_intro: 2
    order: 22
    base_file: I2PD14800.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9334702007765593
    legacy_id: v022
  I2PD14786:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14786
      total_pages: 936
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I2PD14786.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.939106229910021
    legacy_id: v008
  I2PD14784:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14784
      total_pages: 944
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2PD14784.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9326831953022519
    legacy_id: v006
  I2PD14780:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14780
      total_pages: 830
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD14780.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.941721676515095
    legacy_id: v002
  I2PD14789:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14789
      total_pages: 848
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I2PD14789.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9314157345048525
    legacy_id: v011
  I2PD14806:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14806
      total_pages: 790
      volume_number: 28
      volume_pages_bdrc_intro: 2
    order: 28
    base_file: I2PD14806.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9508386190288884
    legacy_id: v028
  I2PD14787:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14787
      total_pages: 816
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I2PD14787.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.947239436008575
    legacy_id: v009
  I2PD14810:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14810
      total_pages: 1099
      volume_number: 32
      volume_pages_bdrc_intro: 2
    order: 32
    base_file: I2PD14810.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9510500623002829
    legacy_id: v032
  I2PD14792:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14792
      total_pages: 838
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I2PD14792.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.928081827773315
    legacy_id: v014
  I2PD14802:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14802
      total_pages: 780
      volume_number: 24
      volume_pages_bdrc_intro: 2
    order: 24
    base_file: I2PD14802.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9154876023392843
    legacy_id: v024
  I2PD14779:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14779
      total_pages: 966
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD14779.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9392640817390465
    legacy_id: v001
  I2PD14794:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14794
      total_pages: 878
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I2PD14794.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9401714092769802
    legacy_id: v016
  I2PD14801:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14801
      total_pages: 1072
      volume_number: 23
      volume_pages_bdrc_intro: 2
    order: 23
    base_file: I2PD14801.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9344543695144
    legacy_id: v023
  I2PD14805:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14805
      total_pages: 832
      volume_number: 27
      volume_pages_bdrc_intro: 2
    order: 27
    base_file: I2PD14805.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9391931103868976
    legacy_id: v027
  I2PD14808:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14808
      total_pages: 808
      volume_number: 30
      volume_pages_bdrc_intro: 2
    order: 30
    base_file: I2PD14808.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9381607910162078
    legacy_id: v030
  I2PD14783:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14783
      total_pages: 968
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2PD14783.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9022798929434716
    legacy_id: v005
  I2PD14790:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14790
      total_pages: 722
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I2PD14790.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9402551704831574
    legacy_id: v012
  I2PD14791:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14791
      total_pages: 802
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I2PD14791.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9364784332410482
    legacy_id: v013
  I2PD14781:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14781
      total_pages: 876
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2PD14781.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.930891846096945
    legacy_id: v003
  I2PD14798:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14798
      total_pages: 930
      volume_number: 20
      volume_pages_bdrc_intro: 2
    order: 20
    base_file: I2PD14798.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9267874257989992
    legacy_id: v020
  I2PD14796:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14796
      total_pages: 826
      volume_number: 18
      volume_pages_bdrc_intro: 2
    order: 18
    base_file: I2PD14796.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9351551252838542
    legacy_id: v018
  I2PD14788:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14788
      total_pages: 966
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I2PD14788.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9417139392186508
    legacy_id: v010
  I2PD14795:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14795
      total_pages: 946
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 17
    base_file: I2PD14795.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9108030340567448
    legacy_id: v017
  I2PD14785:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14785
      total_pages: 982
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I2PD14785.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9401762473397481
    legacy_id: v007
  I2PD14799:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14799
      total_pages: 1000
      volume_number: 21
      volume_pages_bdrc_intro: 2
    order: 21
    base_file: I2PD14799.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9187911377776916
    legacy_id: v021
  I2PD14782:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14782
      total_pages: 708
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2PD14782.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9264980225533062
    legacy_id: v004
  I2PD14803:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14803
      total_pages: 792
      volume_number: 25
      volume_pages_bdrc_intro: 2
    order: 25
    base_file: I2PD14803.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9228030994351915
    legacy_id: v025
  I2PD14793:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14793
      total_pages: 814
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I2PD14793.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9213310397472172
    legacy_id: v015
  I2PD14804:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14804
      total_pages: 786
      volume_number: 26
      volume_pages_bdrc_intro: 2
    order: 26
    base_file: I2PD14804.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9504559587524095
    legacy_id: v026
  I2PD14809:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD14809
      total_pages: 718
      volume_number: 31
      volume_pages_bdrc_intro: 2
    order: 31
    base_file: I2PD14809.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9360786205895755
    legacy_id: v031
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
